/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package books;

/**
 *
 * @author srichard
 */
public class Philippians {
public static String[][] chap(String version)
		{
			String[][] chap = new String[5][ 31];
			if (version.equals("KJV")){
					chap[1][ 1] = "Paul and Timotheus, the servants of Jesus Christ, to all the saints in Christ Jesus which are at Philippi, with the bishops and deacons:";
					chap[1][ 2] = "Grace be unto you, and peace, from God our Father, and from the Lord Jesus Christ.";
					chap[1][ 3] = "I thank my God upon every remembrance of you,";
					chap[1][ 4] = "Always in every prayer of mine for you all making request with joy,";
					chap[1][ 5] = "For your fellowship in the gospel from the first day until now;";
					chap[1][ 6] = "Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ:";
					chap[1][ 7] = "Even as it is meet for me to think this of you all, because I have you in my heart; inasmuch as both in my bonds, and in the defence and confirmation of the gospel, ye all are partakers of my grace.";
					chap[1][ 8] = "For God is my record, how greatly I long after you all in the bowels of Jesus Christ.";
					chap[1][ 9] = "And this I pray, that your love may abound yet more and more in knowledge and in all judgment;";
					chap[1][ 10] = "That ye may approve things that are excellent; that ye may be sincere and without offence till the day of Christ.";
					chap[1][ 11] = "Being filled with the fruits of righteousness, which are by Jesus Christ, unto the glory and praise of God.";
					chap[1][ 12] = "But I would ye should understand, brethren, that the things which happened unto me have fallen out rather unto the furtherance of the gospel;";
					chap[1][ 13] = "So that my bonds in Christ are manifest in all the palace, and in all other places;";
					chap[1][ 14] = "And many of the brethren in the Lord, waxing confident by my bonds, are much more bold to speak the word without fear.";
					chap[1][ 15] = "Some indeed preach Christ even of envy and strife; and some also of good will:";
					chap[1][ 16] = "The one preach Christ of contention, not sincerely, supposing to add affliction to my bonds:";
					chap[1][ 17] = "But the other of love, knowing that I am set for the defence of the gospel.";
					chap[1][ 18] = "What then? notwithstanding, every way, whether in pretence, or in truth, Christ is preached; and I therein do rejoice, yea, and will rejoice.";
					chap[1][ 19] = "For I know that this shall turn to my salvation through your prayer, and the supply of the Spirit of Jesus Christ,";
					chap[1][ 20] = "According to my earnest expectation and my hope, that in nothing I shall be ashamed, but that with all boldness, as always, so now also Christ shall be magnified in my body, whether it be by life, or by death.";
					chap[1][ 21] = "For to me to live is Christ, and to die is gain.";
					chap[1][ 22] = "But if I live in the flesh, this is the fruit of my labour: yet what I shall choose I wot not.";
					chap[1][ 23] = "For I am in a strait betwixt two, having a desire to depart, and to be with Christ; which is far better:";
					chap[1][ 24] = "Nevertheless to abide in the flesh is more needful for you.";
					chap[1][ 25] = "And having this confidence, I know that I shall abide and continue with you all for your furtherance and joy of faith;";
					chap[1][ 26] = "That your rejoicing may be more abundant in Jesus Christ for me by my coming to you again.";
					chap[1][ 27] = "Only let your conversation be as it becometh the gospel of Christ: that whether I come and see you, or else be absent, I may hear of your affairs, that ye stand fast in one spirit, with one mind striving together for the faith of the gospel;";
					chap[1][ 28] = "And in nothing terrified by your adversaries: which is to them an evident token of perdition, but to you of salvation, and that of God.";
					chap[1][ 29] = "For unto you it is given in the behalf of Christ, not only to believe on him, but also to suffer for his sake;";
					chap[1][ 30] = "Having the same conflict which ye saw in me, and now hear to be in me.";
					chap[2][ 1] = "If there be therefore any consolation in Christ, if any comfort of love, if any fellowship of the Spirit, if any bowels and mercies, ";
					chap[2][ 2] = "Fulfil ye my joy, that ye be likeminded, having the same love, being of one accord, of one mind. ";
					chap[2][ 3] = "Let nothing be done through strife or vainglory; but in lowliness of mind let each esteem other better than themselves. ";
					chap[2][ 4] = "Look not every man on his own things, but every man also on the things of others. ";
					chap[2][ 5] = "Let this mind be in you, which was also in Christ Jesus: ";
					chap[2][ 6] = "Who, being in the form of God, thought it not robbery to be equal with God: ";
					chap[2][ 7] = "But made himself of no reputation, and took upon him the form of a servant, and was made in the likeness of men: ";
					chap[2][ 8] = "And being found in fashion as a man, he humbled himself, and became obedient unto death, even the death of the cross. ";
					chap[2][ 9] = "Wherefore God also hath highly exalted him, and given him a name which is above every name: ";
					chap[2][ 10] = "That at the name of Jesus every knee should bow, of things in heaven, and things in earth, and things under the earth; ";
					chap[2][ 11] = "And that every tongue should confess that Jesus Christ is Lord, to the glory of God the Father. ";
					chap[2][ 12] = "Wherefore, my beloved, as ye have always obeyed, not as in my presence only, but now much more in my absence, work out your own salvation with fear and trembling. ";
					chap[2][ 13] = "For it is God which worketh in you both to will and to do of his good pleasure. ";
					chap[2][ 14] = "Do all things without murmurings and disputings: ";
					chap[2][ 15] = "That ye may be blameless and harmless, the sons of God, without rebuke, in the midst of a crooked and perverse nation, among whom ye shine as lights in the world; ";
					chap[2][ 16] = "Holding forth the word of life; that I may rejoice in the day of Christ, that I have not run in vain, neither laboured in vain. ";
					chap[2][ 17] = "Yea, and if I be offered upon the sacrifice and service of your faith, I joy, and rejoice with you all. ";
					chap[2][ 18] = "For the same cause also do ye joy, and rejoice with me. ";
					chap[2][ 19] = "But I trust in the Lord Jesus to send Timotheus shortly unto you, that I also may be of good comfort, when I know your state. ";
					chap[2][ 20] = "For I have no man likeminded, who will naturally care for your state. ";
					chap[2][ 21] = "For all seek their own, not the things which are Jesus Christ's. ";
					chap[2][ 22] = "But ye know the proof of him, that, as a son with the father, he hath served with me in the gospel. ";
					chap[2][ 23] = "Him therefore I hope to send presently, so soon as I shall see how it will go with me. ";
					chap[2][ 24] = "But I trust in the Lord that I also myself shall come shortly. ";
					chap[2][ 25] = "Yet I supposed it necessary to send to you Epaphroditus, my brother, and companion in labour, and fellowsoldier, but your messenger, and he that ministered to my wants. ";
					chap[2][ 26] = "For he longed after you all, and was full of heaviness, because that ye had heard that he had been sick. ";
					chap[2][ 27] = "For indeed he was sick nigh unto death: but God had mercy on him; and not on him only, but on me also, lest I should have sorrow upon sorrow. ";
					chap[2][ 28] = "I sent him therefore the more carefully, that, when ye see him again, ye may rejoice, and that I may be the less sorrowful. ";
					chap[2][ 29] = "Receive him therefore in the Lord with all gladness; and hold such in reputation: ";
					chap[2][ 30] = "Because for the work of Christ he was nigh unto death, not regarding his life, to supply your lack of service toward me.";
					chap[3][ 1] = "Finally, my brethren, rejoice in the Lord. To write the same things to you, to me indeed is not grievous, but for you it is safe. ";
					chap[3][ 2] = "Beware of dogs, beware of evil workers, beware of the concision. ";
					chap[3][ 3] = "For we are the circumcision, which worship God in the spirit, and rejoice in Christ Jesus, and have no confidence in the flesh. ";
					chap[3][ 4] = "Though I might also have confidence in the flesh. If any other man thinketh that he hath whereof he might trust in the flesh, I more: ";
					chap[3][ 5] = "Circumcised the eighth day, of the stock of Israel, of the tribe of Benjamin, an Hebrew of the Hebrews; as touching the law, a Pharisee; ";
					chap[3][ 6] = "Concerning zeal, persecuting the church; touching the righteousness which is in the law, blameless. ";
					chap[3][ 7] = "But what things were gain to me, those I counted loss for Christ. ";
					chap[3][ 8] = "Yea doubtless, and I count all things but loss for the excellency of the knowledge of Christ Jesus my Lord: for whom I have suffered the loss of all things, and do count them but dung, that I may win Christ, ";
					chap[3][ 9] = "And be found in him, not having mine own righteousness, which is of the law, but that which is through the faith of Christ, the righteousness which is of God by faith: ";
					chap[3][ 10] = "That I may know him, and the power of his resurrection, and the fellowship of his sufferings, being made conformable unto his death; ";
					chap[3][ 11] = "If by any means I might attain unto the resurrection of the dead. ";
					chap[3][ 12] = "Not as though I had already attained, either were already perfect: but I follow after, if that I may apprehend that for which also I am apprehended of Christ Jesus. ";
					chap[3][ 13] = "Brethren, I count not myself to have apprehended: but this one thing I do, forgetting those things which are behind, and reaching forth unto those things which are before, ";
					chap[3][ 14] = "I press toward the mark for the prize of the high calling of God in Christ Jesus. ";
					chap[3][ 15] = "Let us therefore, as many as be perfect, be thus minded: and if in any thing ye be otherwise minded, God shall reveal even this unto you. ";
					chap[3][ 16] = "Nevertheless, whereto we have already attained, let us walk by the same rule, let us mind the same thing. ";
					chap[3][ 17] = "Brethren, be followers together of me, and mark them which walk so as ye have us for an example. ";
					chap[3][ 18] = "(For many walk, of whom I have told you often, and now tell you even weeping, that they are the enemies of the cross of Christ: ";
					chap[3][ 19] = "Whose end is destruction, whose God is their belly, and whose glory is in their shame, who mind earthly things.) ";
					chap[3][ 20] = "For our conversation is in heaven; from whence also we look for the Saviour, the Lord Jesus Christ: ";
					chap[3][ 21] = "Who shall change our vile body, that it may be fashioned like unto his glorious body, according to the working whereby he is able even to subdue all things unto himself.";
					chap[4][ 1] = "Therefore, my brethren dearly beloved and longed for, my joy and crown, so stand fast in the Lord, my dearly beloved. ";
					chap[4][ 2] = "I beseech Euodias, and beseech Syntyche, that they be of the same mind in the Lord. ";
					chap[4][ 3] = "And I intreat thee also, true yokefellow, help those women which laboured with me in the gospel, with Clement also, and with other my fellowlabourers, whose names are in the book of life. ";
					chap[4][ 4] = "Rejoice in the Lord always: and again I say, Rejoice. ";
					chap[4][ 5] = "Let your moderation be known unto all men. The Lord is at hand. ";
					chap[4][ 6] = "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. ";
					chap[4][ 7] = "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus. ";
					chap[4][ 8] = "Finally, brethren, whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, whatsoever things are of good report; if there be any virtue, and if there be any praise, think on these things. ";
					chap[4][ 9] = "Those things, which ye have both learned, and received, and heard, and seen in me, do: and the God of peace shall be with you. ";
					chap[4][ 10] = "But I rejoiced in the Lord greatly, that now at the last your care of me hath flourished again; wherein ye were also careful, but ye lacked opportunity. ";
					chap[4][ 11] = "Not that I speak in respect of want: for I have learned, in whatsoever state I am, therewith to be content. ";
					chap[4][ 12] = "I know both how to be abased, and I know how to abound: every where and in all things I am instructed both to be full and to be hungry, both to abound and to suffer need. ";
					chap[4][ 13] = "I can do all things through Christ which strengtheneth me. ";
					chap[4][ 14] = "Notwithstanding ye have well done, that ye did communicate with my affliction. ";
					chap[4][ 15] = "Now ye Philippians know also, that in the beginning of the gospel, when I departed from Macedonia, no church communicated with me as concerning giving and receiving, but ye only. ";
					chap[4][ 16] = "For even in Thessalonica ye sent once and again unto my necessity. ";
					chap[4][ 17] = "Not because I desire a gift: but I desire fruit that may abound to your account. ";
					chap[4][ 18] = "But I have all, and abound: I am full, having received of Epaphroditus the things which were sent from you, an odour of a sweet smell, a sacrifice acceptable, wellpleasing to God. ";
					chap[4][ 19] = "But my God shall supply all your need according to his riches in glory by Christ Jesus. ";
					chap[4][ 20] = "Now unto God and our Father be glory for ever and ever. Amen. ";
					chap[4][ 21] = "Salute every saint in Christ Jesus. The brethren which are with me greet you. ";
					chap[4][ 22] = "All the saints salute you, chiefly they that are of Caesar's household. ";
					chap[4][ 23] = "The grace of our Lord Jesus Christ be with you all. Amen.";
}
if (version.equals("NIV")){

					chap[1][ 1] = "Paul and Timothy, servants of Christ Jesus, To all the saints in Christ Jesus at Philippi, together with the overseers and deacons:";
					chap[1][ 2] = "Grace and peace to you from God our Father and the Lord Jesus Christ.";
					chap[1][ 3] = "I thank my God every time I remember you.";
					chap[1][ 4] = "In all my prayers for all of you, I always pray with joy";
					chap[1][ 5] = "because of your partnership in the gospel from the first day until now,";
					chap[1][ 6] = "being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus.";
					chap[1][ 7] = "It is right for me to feel this way about all of you, since I have you in my heart; for whether I am in chains or defending and confirming the gospel, all of you share in God's grace with me.";
					chap[1][ 8] = "God can testify how I long for all of you with the affection of Christ Jesus.";
					chap[1][ 9] = "And this is my prayer: that your love may abound more and more in knowledge and depth of insight,";
					chap[1][ 10] = "so that you may be able to discern what is best and may be pure and blameless until the day of Christ,";
					chap[1][ 11] = "filled with the fruit of righteousness that comes through Jesus Christ—to the glory and praise of God.";
					chap[1][ 12] = "Now I want you to know, brothers, that what has happened to me has really served to advance the gospel.";
					chap[1][ 13] = "As a result, it has become clear throughout the whole palace guard and to everyone else that I am in chains for Christ.";
					chap[1][ 14] = "Because of my chains, most of the brothers in the Lord have been encouraged to speak the word of God more courageously and fearlessly.";
					chap[1][ 15] = "It is true that some preach Christ out of envy and rivalry, but others out of goodwill.";
					chap[1][ 16] = "The latter do so in love, knowing that I am put here for the defense of the gospel.";
					chap[1][ 17] = "The former preach Christ out of selfish ambition, not sincerely, supposing that they can stir up trouble for me while I am in chains.";
					chap[1][ 18] = "But what does it matter? The important thing is that in every way, whether from false motives or true, Christ is preached. And because of this I rejoice. Yes, and I will continue to rejoice,";
					chap[1][ 19] = "for I know that through your prayers and the help given by the Spirit of Jesus Christ, what has happened to me will turn out for my deliverance.";
					chap[1][ 20] = "I eagerly expect and hope that I will in no way be ashamed, but will have sufficient courage so that now as always Christ will be exalted in my body, whether by life or by death.";
					chap[1][ 21] = "For to me, to live is Christ and to die is gain.";
					chap[1][ 22] = "If I am to go on living in the body, this will mean fruitful labor for me. Yet what shall I choose? I do not know!";
					chap[1][ 23] = "I am torn between the two: I desire to depart and be with Christ, which is better by far;";
					chap[1][ 24] = "but it is more necessary for you that I remain in the body.";
					chap[1][ 25] = "Convinced of this, I know that I will remain, and I will continue with all of you for your progress and joy in the faith,";
					chap[1][ 26] = "so that through my being with you again your joy in Christ Jesus will overflow on account of me.";
					chap[1][ 27] = "Whatever happens, conduct yourselves in a manner worthy of the gospel of Christ. Then, whether I come and see you or only hear about you in my absence, I will know that you stand firm in one spirit, contending as one man for the faith of the gospel";
					chap[1][ 28] = "without being frightened in any way by those who oppose you. This is a sign to them that they will be destroyed, but that you will be saved—and that by God.";
					chap[1][ 29] = "For it has been granted to you on behalf of Christ not only to believe on him, but also to suffer for him,";
					chap[1][ 30] = "since you are going through the same struggle you saw I had, and now hear that I still have.";
					chap[2][ 1] = "If you have any encouragement from being united with Christ, if any comfort from his love, if any fellowship with the Spirit, if any tenderness and compassion,";
					chap[2][ 2] = "then make my joy complete by being like-minded, having the same love, being one in spirit and purpose.";
					chap[2][ 3] = "Do nothing out of selfish ambition or vain conceit, but in humility consider others better than yourselves.";
					chap[2][ 4] = "Each of you should look not only to your own interests, but also to the interests of others.";
					chap[2][ 5] = "Your attitude should be the same as that of Christ Jesus: ";
					chap[2][ 6] = "Who, being in very nature God, did not consider equality with God something to be grasped, ";
					chap[2][ 7] = "but made himself nothing, taking the very nature of a servant, being made in human likeness. ";
					chap[2][ 8] = "And being found in appearance as a man, he humbled himself and became obedient to death— even death on a cross!";
					chap[2][ 9] = "Therefore God exalted him to the highest place and gave him the name that is above every name,";
					chap[2][ 10] = "that at the name of Jesus every knee should bow, in heaven and on earth and under the earth,";
					chap[2][ 11] = "and every tongue confess that Jesus Christ is Lord, to the glory of God the Father.";
					chap[2][ 12] = "Therefore, my dear friends, as you have always obeyed—not only in my presence, but now much more in my absence—continue to work out your salvation with fear and trembling,";
					chap[2][ 13] = "for it is God who works in you to will and to act according to his good purpose.";
					chap[2][ 14] = "Do everything without complaining or arguing,";
					chap[2][ 15] = "so that you may become blameless and pure, children of God without fault in a crooked and depraved generation, in which you shine like stars in the universe";
					chap[2][ 16] = "as you hold out the word of life—in order that I may boast on the day of Christ that I did not run or labor for nothing.";
					chap[2][ 17] = "But even if I am being poured out like a drink offering on the sacrifice and service coming from your faith, I am glad and rejoice with all of you.";
					chap[2][ 18] = "So you too should be glad and rejoice with me.";
					chap[2][ 19] = "I hope in the Lord Jesus to send Timothy to you soon, that I also may be cheered when I receive news about you.";
					chap[2][ 20] = "I have no one else like him, who takes a genuine interest in your welfare.";
					chap[2][ 21] = "For everyone looks out for his own interests, not those of Jesus Christ.";
					chap[2][ 22] = "But you know that Timothy has proved himself, because as a son with his father he has served with me in the work of the gospel.";
					chap[2][ 23] = "I hope, therefore, to send him as soon as I see how things go with me.";
					chap[2][ 24] = "And I am confident in the Lord that I myself will come soon.";
					chap[2][ 25] = "But I think it is necessary to send back to you Epaphroditus, my brother, fellow worker and fellow soldier, who is also your messenger, whom you sent to take care of my needs.";
					chap[2][ 26] = "For he longs for all of you and is distressed because you heard he was ill.";
					chap[2][ 27] = "Indeed he was ill, and almost died. But God had mercy on him, and not on him only but also on me, to spare me sorrow upon sorrow.";
					chap[2][ 28] = "Therefore I am all the more eager to send him, so that when you see him again you may be glad and I may have less anxiety.";
					chap[2][ 29] = "Welcome him in the Lord with great joy, and honor men like him,";
					chap[2][ 30] = "because he almost died for the work of Christ, risking his life to make up for the help you could not give me.";
					chap[3][ 1] = "Finally, my brothers, rejoice in the Lord! It is no trouble for me to write the same things to you again, and it is a safeguard for you.";
					chap[3][ 2] = "Watch out for those dogs, those men who do evil, those mutilators of the flesh.";
					chap[3][ 3] = "For it is we who are the circumcision, we who worship by the Spirit of God, who glory in Christ Jesus, and who put no confidence in the flesh—";
					chap[3][ 4] = "though I myself have reasons for such confidence. If anyone else thinks he has reasons to put confidence in the flesh, I have more:";
					chap[3][ 5] = "circumcised on the eighth day, of the people of Israel, of the tribe of Benjamin, a Hebrew of Hebrews; in regard to the law, a Pharisee;";
					chap[3][ 6] = "as for zeal, persecuting the church; as for legalistic righteousness, faultless.";
					chap[3][ 7] = "But whatever was to my profit I now consider loss for the sake of Christ.";
					chap[3][ 8] = "What is more, I consider everything a loss compared to the surpassing greatness of knowing Christ Jesus my Lord, for whose sake I have lost all things. I consider them rubbish, that I may gain Christ";
					chap[3][ 9] = "and be found in him, not having a righteousness of my own that comes from the law, but that which is through faith in Christ—the righteousness that comes from God and is by faith.";
					chap[3][ 10] = "I want to know Christ and the power of his resurrection and the fellowship of sharing in his sufferings, becoming like him in his death,";
					chap[3][ 11] = "and so, somehow, to attain to the resurrection from the dead.";
					chap[3][ 12] = "Not that I have already obtained all this, or have already been made perfect, but I press on to take hold of that for which Christ Jesus took hold of me.";
					chap[3][ 13] = "Brothers, I do not consider myself yet to have taken hold of it. But one thing I do: Forgetting what is behind and straining toward what is ahead,";
					chap[3][ 14] = "I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus. ";
					chap[3][ 15] = "All of us who are mature should take such a view of things. And if on some point you think differently, that too God will make clear to you.";
					chap[3][ 16] = "Only let us live up to what we have already attained. ";
					chap[3][ 17] = "Join with others in following my example, brothers, and take note of those who live according to the pattern we gave you.";
					chap[3][ 18] = "For, as I have often told you before and now say again even with tears, many live as enemies of the cross of Christ.";
					chap[3][ 19] = "Their destiny is destruction, their god is their stomach, and their glory is in their shame. Their mind is on earthly things.";
					chap[3][ 20] = "But our citizenship is in heaven. And we eagerly await a Savior from there, the Lord Jesus Christ,";
					chap[3][ 21] = "who, by the power that enables him to bring everything under his control, will transform our lowly bodies so that they will be like his glorious body.";
					chap[4][ 1] = "Therefore, my brothers, you whom I love and long for, my joy and crown, that is how you should stand firm in the Lord, dear friends!";
					chap[4][ 2] = "I plead with Euodia and I plead with Syntyche to agree with each other in the Lord.";
					chap[4][ 3] = "Yes, and I ask you, loyal yokefellow,[a] help these women who have contended at my side in the cause of the gospel, along with Clement and the rest of my fellow workers, whose names are in the book of life. ";
					chap[4][ 4] = "Rejoice in the Lord always. I will say it again: Rejoice!";
					chap[4][ 5] = "Let your gentleness be evident to all. The Lord is near.";
					chap[4][ 6] = "Do not be anxious about anything, but in everything, by prayer and petition, with thanksgiving, present your requests to God.";
					chap[4][ 7] = "And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus. ";
					chap[4][ 8] = "Finally, brothers, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable—if anything is excellent or praiseworthy—think about such things.";
					chap[4][ 9] = "Whatever you have learned or received or heard from me, or seen in me—put it into practice. And the God of peace will be with you.";
					chap[4][ 10] = "I rejoice greatly in the Lord that at last you have renewed your concern for me. Indeed, you have been concerned, but you had no opportunity to show it.";
					chap[4][ 11] = "I am not saying this because I am in need, for I have learned to be content whatever the circumstances.";
					chap[4][ 12] = "I know what it is to be in need, and I know what it is to have plenty. I have learned the secret of being content in any and every situation, whether well fed or hungry, whether living in plenty or in want.";
					chap[4][ 13] = "I can do everything through him who gives me strength.";
					chap[4][ 14] = "Yet it was good of you to share in my troubles.";
					chap[4][ 15] = "Moreover, as you Philippians know, in the early days of your acquaintance with the gospel, when I set out from Macedonia, not one church shared with me in the matter of giving and receiving, except you only;";
					chap[4][ 16] = "for even when I was in Thessalonica, you sent me aid again and again when I was in need. ";
					chap[4][ 17] = "Not that I am looking for a gift, but I am looking for what may be credited to your account.";
					chap[4][ 18] = "I have received full payment and even more; I am amply supplied, now that I have received from Epaphroditus the gifts you sent. They are a fragrant offering, an acceptable sacrifice, pleasing to God.";
					chap[4][ 19] = "And my God will meet all your needs according to his glorious riches in Christ Jesus. ";
					chap[4][ 20] = "To our God and Father be glory for ever and ever. Amen.";
					chap[4][ 21] = "Greet all the saints in Christ Jesus. The brothers who are with me send greetings.";
					chap[4][ 22] = "All the saints send you greetings, especially those who belong to Caesar's household.";
					chap[4][ 23] = "The grace of the Lord Jesus Christ be with your spirit. Amen.";

			}
            return chap;
		}

}